before_build:
- nuget restore
- choco install opencover.portable
- choco install codecov

pull_requests:
  do_not_increment_build_number: true
skip_non_tags: true
image: Visual Studio 2019
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build_script:
- cmd: >-
    dotnet --version
    dotnet build --verbosity m 
# test_script:
# - env: >-
#     CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
# - cmd: >-
#     dotnet test --verbosity normal
    
# build:
#   project: ProjectCleanArch.sln
#   verbosity: minimal
  
test_script:
- OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:".src\Core\ProjectCleanArch.Domain.Test\bin\Debug\ProjectCleanArch.Domain.Test.dll -noshadow" -filter:"+[ProjectCleanArch.Domain.Test*]* -[ProjectCleanArch.Domain.Test*]*" -output:".\ProjectCleanArch.xml"
- codecov -f "ProjectCleanArch.xml"

